site_name: TibiaKt
repo_url: https://github.com/Galarzaa90/TibiaKt
repo_name: Galarzaa90/TibiaKt

theme:
  name: material
  language: en
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: light blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: light blue
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  icon:
    repo: fontawesome/brands/github
  features:
    - content.code.copy
    - navigation.footer
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.suggest
    - search.highlight
    - search.share
    - toc.follow

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Galarzaa90/TibiaKt
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/r/galarzaa90/tibiakt


plugins:
  - search

watch:
  - docs
  - mkdocs.yaml

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.snippets
  - toc:
      permalink: true
